import localFont from "next/font/local";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs" 
import Footer from "@/components/ui/footer";

// Load custom fonts from local files
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",   // Path to the font file
  variable: "--font-geist-sans", // CSS variable name for the font
  weight: "100 900",             // Font weight range
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",  // Path to the font file
  variable: "--font-geist-mono",    // CSS variable name for the font
  weight: "100 900",                // Font weight range
});

// Metadata for the application
export const metadata = {
  title: "Trivia Quiz GPT",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <Footer/>
      </body>
    </html>
    </ClerkProvider>
  );
}
